### PR TITLE
Added a little result bar 

### PR DESCRIPTION
**Pull request by sudo-Mystic**
image

### CODE REVIEW

**Comment by itsMathew** [comment]
maybe you can add a grey section in this for the skipped questions

**Comment by sudo-Mystic** [comment]
> maybe you can add a grey section in this for the skipped questions

Added 👍
image

**Comment by nikhilmwarrier** [comment]
LGTM so far but can you PR to the dev branch instead?

**Comment by sudo-Mystic** [comment]
> LGTM so far but can you PR to the dev branch instead?

alright

**Pull request closed without merging**
